server:
  port: 8080
  content-path: astro-broker

spring:
  application:
    name: astro-broker
  cloud:
    aws:
      region:
        static: ${AWS_REGION:us-east-1}
      credentials:
        profile:
          name: ${AWS_CREDINTIALS_PROFILE_NAME:astro-sqs}
      sqs:
        listener:
          max-concurrent-messages: 5
          max-messages-per-poll: 5
          poll-timeout: 10s
          max-delay-between-polls: 10s
          max-inflight-messages-per-queue: 10
          acknowledgement-mode: ON_SUCCESS
          acknowledgement-interval: 1s
          acknowledgement-threshold: 10
          acknowledgement-order: PARALLEL
          message-visibility: 60s
          queue-not-found-strategy: FAIL

app:
  publisher:
    kafka:
      url: ''
      destination: ''
    sqs:
      url: ${AWS_SQS_URL}
      destination: ${AWS_SQS_QUEUE_NAME:bac-portal-massa-discovery}