server:
  port: 8080
  content-path: astro-broker

spring:
  application:
    name: astro-broker
  cloud:
    aws:
      region:
        static: ${AWS_REGION:us-east-1}
      credentials:
        profile:
          name: ${AWS_CREDINTIALS_PROFILE_NAME:astro-sqs}

app:
  consumer:
    broker:
      rabbitmq:
        url: ${RABBITMQ_URL:amqps://guest:guest@localhost:5672/exchange}
        destination: ${BROKER_DESTINATION:csg-ws-bac-portal-massa-discovery}
      kafka:
        url: ${KAFKA_URL:localhost:9092}
        destination: ${BROKER_DESTINATION:csg-ws-bac-portal-massa-discovery}
        group-id: ${KAFKA_GROUP_ID:astro-consumer}
      sqs:
        url: ${AWS_SQS_URL}
        destination: ${BROKER_DESTINATION:csg-ws-bac-portal-massa-discovery}
  producer:
    broker:
      rabbitmq:
        url: ${RABBITMQ_URL:amqps://guest:guest@localhost:5672/exchange}
      kafka:
        url: ${KAFKA_URL:localhost:9092}
      sqs:
        url: ${AWS_SQS_URL:fake}